baseURL = "https://winnipeg.urbanism-guide.com/"
title = "Winnipeg Urbanism Guide"

[module]
[[module.imports]]
path = "github.com/prestomation/urbanism-guide-core"

[params]
  description = "A practical guide for Winnipeg urbanists and advocates. Understand the issues, learn the terms, and show up ready to contribute."
  goatCounterCode = "winnipeg-urbanism-guide"
  BookRepo = "https://github.com/prestomation/winnipeg-urbanism-guide"
  BookEditPath = "edit/main/content"
