name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    uses: prestomation/urbanism-guide-core/.github/workflows/deploy.yml@v0.1.5
    with:
      timezone: "America/Winnipeg"
