name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    permissions:
      contents: write
    uses: prestomation/urbanism-guide-core/.github/workflows/pr-preview-cleanup.yml@v0.3.1
