name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    permissions:
      contents: write
      pull-requests: write
    uses: prestomation/urbanism-guide-core/.github/workflows/pr-preview.yml@v0.1.5
    with:
      timezone: "America/Winnipeg"
      base_url: "https://winnipeg.urbanism-guide.com"
      run_link_check: false
